packageExtensions:
  # Lots of things depend on debug but don't peerDep supports-color
  debug@*:
    dependencies:
      supports-color: ^7.2.0
  mongodb@*:
    dependencies:
      aws4: ^1.10.1
      mongodb-client-encryption: ^1.1.0
  styled-components@*:
    dependencies:
      react-is: ^16.13.1
  ws@*:
    dependencies:
      bufferutil: ^4.0.1
      utf-8-validate: ^5.0.2
  rc-slider@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-tooltip@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-util@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  rc-trigger@*:
    peerDependencies:
      react: '*'
      react-dom: '*'
  react-redux@*:
    peerDependencies:
      redux: '*'
  '@thematic/fluent@*':
    peerDependencies:
      '@uifabric/icons': '*'
  '@uifabric/styling@*':
    peerDependencies: 
      react: '*'
  '@uifabric/icons@*':
    peerDependencies: 
      react: '*'
  '@apollo/link-batch@*':
    peerDependencies:
      graphql: '*'
  '@apollo/link-context@*':
    peerDependencies:
      graphql: '*'
  '@essex-js-toolkit/themed-components@*':
    peerDependencies:
      office-ui-fabric-react: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
