pool:
  vmImage: 'windows-latest'

steps:
  # Scan for Security Credentials
  - task: CredScan@3
    inputs:
      outputFormat: sarif
      debugMode: false

  # MS Security Checks
  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

  - task: PublishSecurityAnalysisLogs@3
    inputs:
      ArtifactName: 'CodeAnalysisLogs'
      ArtifactType: 'Container'
