# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: pnpm CI
        run: pnpm ci
        env:
          AUTH_AUTHORITY: ${{ secrets.AUTH_AUTHORITY }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH_REDIRECT_URI: ${{ secrets.AUTH_REDIRECT_URI }}
          CLIENT_CD_ENABLED: true
          SERVER_CD_ENABLED: true
          GRAPHQL_API: ${{ secrets.GRAPHQL_API }}

      - name: Deploy Client
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          pnpm deploy --filter @newsthreads/client -- \
          --storageAccount ${{ secrets.CLIENT_DEPLOY_AZURE_CONTAINER }} \
          --storageAccountKey ${{ secrets.CLIENT_DEPLOY_AZURE_CONTAINER_KEY }}

      - name: Deploy Server
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: Azure/functions-action@v1.1.5
        with:
          app-name: ${{ secrets.SERVER_DEPLOY_AZURE_FUNCTION_APPNAME }}
          package: ${{ github.workspace }}/packages/server/deploy.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
